-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- USE ecommerce_db
USE ecommerce_db

-- DROP DATABASE ecommerce_db
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS ProductTag;

-- -- CREATING THE NEW DATABASE
-- CREATE TABLE Category(
--     id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     category_name VARCHAR (30) NOT NULL
-- );

-- CREATE TABLE Product(
-- id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
-- product_name VARCHAR(30) NOT NULL,
-- price DECIMAL(10,2) NOT NULL VALIDATION,
-- stock INTEGER DEFAULT(10) NOT NULL VALIDATION,
-- FOREIGN KEY (category_id) REFERENCES category(id)
-- );

-- CREATE TABLE Tag(
--     id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     tag_name VAR(30)
-- );

-- CREATE TABLE ProductTag(
--     id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
--     FOREIGN KEY (product_id) REFERENCES product(id)
--     FOREIGN KEY (tag_id) REFERENCES tag(id)
-- );